name: product_feed
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  async_redux: ^13.2.2
  chopper: ^4.0.4
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  http: ^0.13.4
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: 2.1.7
  chopper_generator:
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: 6.1.3

flutter:
  uses-material-design: true

dependency_overrides:
  analyzer: 3.0.0
